### PR TITLE
General cleanup to make things more ruby-ish

### PR DESCRIPTION
**Pull request by eric**
- Make `require` statements assume `lib/` is in the `$LOAD_PATH`
- Remove the methods in the `Metrics::Instruments` module — there isn't a big
  benefit of using the `register` methods over just having the methods create
  instances of the objects that are needed right there. This also makes it
  possible to have more than one instance of `Metrics::Agent` in a process
- Remove base classes for instruments and statistics — these don't really
  provide value in ruby
- Provide an `#as_json` method along with the `#to_json` to fit in with the
  ActiveSupport JSON model (and also makes it easier for in-process consumers
  that don't want JSON to fetch the data)

### CODE REVIEW

**Comment by eric** [comment]
Would you like me to remove the JSON-related changes to this pull request?

**Comment by mtodd** [comment]
We could define `serializable_hash` instead and alias it as `as_json`.

**Comment by eric** [comment]
Are these changes something you would consider merging?

**Comment by jnunemaker** [comment]
I'd like to see these too, not that this pull requests needs voting. :)

**Comment by mtodd** [comment]
`serializable_hash` is a more generic method idiom used by ActiveSupport that we could use. I'd prefer we use that to generate the actual data and then `as_json` will call that.

Everything else looks pretty solid, so :+1: from me.

**Comment by eric** [comment]
Cool. I'll update for that.

**Comment by mtodd** [comment]
Also, MultiJSON looks like a good option and will simplify integration and improve performance for people using YAJL.

Should be a separate pull request though, right?

**Comment by eric** [comment]
I've made the json-less change to #27.

Is this ready to be merged?

**Comment by eric** [comment]
I also wanted to point out that `as_json` seems to be what ActiveSupport uses:

https://github.com/rails/rails/blob/master/activesupport/lib/active_support/json/encoding.rb

I don't see any reference to `serializable_hash` in ActiveSupport.

@mtodd: Could you point me to where that is?

**Comment by johnewart** [comment]
I'm happy to switch, but there was a lot going on in this patch and I've (unfortunately) been insanely busy -- can you re-base this against the new master which has your other changes in it now?

I just don't want to break existing behavior for folks since this is still minor release increments. Can we add them side-by-side and then phase out the other ones later?

**Comment by eric** [comment]
I've opened pull request #28 to solve the rest of this. I'm closing this now.

**Pull request closed without merging**
