### PR TITLE
Adds heartbeat instrument

### PR DESCRIPTION
**Pull request by BinaryPaean**
Added tests & simple heartbeat instrument to the suite. I also had to make a few changes to get the test suite working nicely for RVM/OSX. I tried to make those changes transparent to other platforms, but let me know if I did something boneheaded by accident.

I'm not sure about the etiquette on the Gemfile.lock, so I included changes there, although you might want to ignore those.

### CODE REVIEW

**Comment by mtodd** [comment]
The `Heartbeat` instrument here is similar to the `Gauge` instrument, I believe. Any reason to not use that?

For example:

``` ruby
@heartbeat = @agent.gauge(:heartbeat){ Time.now }
@heartbeat.get
```

Alternatively, you could also use a meter to mark your heartbeats and just check that the rate doesn't fall below your desired threshold.

**Comment by BinaryPaean** [comment]
It is definitely a subset of the <code>gauge</code> instrument; a bit of syntactic sugar for that particular usage case, really. In light of wanting a small code base, it may not be worth it. Cherry picking <code>9c68178</code> for RVM users is probably still desirable, though.

**Comment by mtodd** [comment]
Does Bundler's `binstubs` conflict with RVM? Also, it's weird to bundle both autotest configuration with a meaningful patch.

I think one goal would be to make it easier to add custom instruments (there are some pull requests that do this). That way a heartbeat, though it may or may not fit into the core distribution, it can easily be added locally or as a separate gem.

**Comment by BinaryPaean** [comment]
It isn't that the binstubs conflict with RVM inherently, but that <code>simplecoverage</code> and <code>autotest</code> will both include/watch (respectively) the folder, leading to bogus coverage information in one case, and excessive activity in the latter.

Bundler's executables won't conflict with RVM gems as long as <code>bundle exec</code> is used, although they will effectively shadow RVM system gems, as intended.

**Comment by mtodd** [comment]
Nice. Looks good. `binstubs` is a Bundler option though, right? Also, would be nice if that were described in the pull request, and maybe two different pull requests be made, one for fixing `binstubs`, and one for the heartbeat feature (so we don't end up with confusing conversations like this).

Honestly, I'm not a user of autotest and not necessarily a fan of adding it to the development dependencies. I'd be much more likely to pull something like that in in my own gem if it were a pull request by itself, though. This one just feels kinda sneaky, right? :)

The `binstubs` portion of the first commit does look good, though.

**Comment by BinaryPaean** [comment]
Correct, <code>binstubs</code> is generated by bundler.

I agree, this pull was a bit of a goofball. For my part, because I'm learning git from mercurial so I wasn't branching habitually enough to easily separate the two changes.

At first, I wasn't expecting to make changes beyond adding <code>heartbeat</code> at first, but I found the test suite wouldn't run out of the box under <code>bundle exec</code> - implying it had some test dependencies that weren't captured in the bundle. Pulling in <code>ZenTest</code> was the short path to getting the tests working.

I'll close this, rebase master, and see if I can get cleaner commits for getting the test suite running with bundle/RVM.

**Pull request closed without merging**
