### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by ColinDKelley**
I am hoping to add graphite support (statsd and/or Sensu). As a foundation, I took this pass to make the code follow Ruby idioms a bit more.

### CODE REVIEW

**Comment by johnewart** [comment]
Thanks! That's a big one -- I'll take a look later today, probably after lunch ;)

**Comment by ColinDKelley** [comment]
Great. BTW I'm happy to help with getting thread safety in next as well, either with ruby-atomic or with lower-level synchronization primitives.

**Comment by johnewart** [comment]
:+1:

**Comment by johnewart** [comment]
Also, sounds good re: thread safety - I haven't had time to do this (though I've been putting time into this again lately) but would love to have it in there.

**Comment by swistaczek** [comment]
@ColinDKelley could you please provide some update on readme files with instructions how to add backend like statsd?

**Comment by johnewart** [comment]
If you want to create a new reporter for StatsD, you would need to implement something with the _report_ method as seen in https://github.com/johnewart/ruby-metrics/blob/master/lib/ruby-metrics/reporters/opentsdb.rb and then add a gem build for it (to keep dependencies restricted to the ones you need for the actual reporter). I've been meaning to create one for statsd at some point but haven't gotten to it so I'll open a new issue for that; it should be pretty easy to add.

**Comment by ColinDKelley** [comment]
@johnewart  Thanks for responding. We're using the statsd-ruby gem which has worked well. BTW we are hoping to remove statsd from our stack in the coming months since it adds little to no value over ruby-metrics, and it trips us up every month or so because it will continue to publish gauge values even if the originating process has been stopped.

**Pull request merged**
